name: aws-env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::biopython
  - conda-forge::markdown
  - conda-forge::pymdown-extensions
  - conda-forge::pygments
  - bioconda::fastqc
  - bioconda::multiqc
  - bioconda::lofreq
  - bioconda::bwa
  - bioconda::t_coffee
  - bioconda::snpeff=4.5covid19
  - bioconda::clustalo
  - conda-forge::nodejs
